### PR TITLE
Update cleanup query for AWS buckets

### PR DESCRIPTION
**Pull request by mc-nv**
#### Checklist
- [x] PR title reflects the change and is of format `<commit_type>: <Title>`
- [ ] Changes are described in the pull request.
- [ ] Related issues are referenced.
- [ ] Populated [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) field
- [ ] Added [test plan](#test-plan) and verified test passes.
- [ ] Verified that the PR passes existing CI.
- [ ] Verified copyright is correct on all changed files.
- [ ] Added _succinct_ git squash message before merging [ref](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [ ] All template sections are filled out.
- [ ] Optional: Additional screenshots for behavior/output changes with before/after.

#### Commit Type:
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] revert
- [ ] style
- [ ] test

#### Test plan:

- CI Pipeline ID:

#### Related Issues: (use one of the action keywords Closes / Fixes / Resolves / Relates to)
- closes GitHub issue: #xxx

### CODE REVIEW

**Comment by kthui** [comment]
I think we can group the remove logic into a function like the [upload on GCS](https://github.com/triton-inference-server/server/blob/main/qa/common/util.sh#L471-L476), so it can be easily implemented by other AWS tests in the future.

**Comment by mc-nv** [comment]
> I think we can group the remove logic into a function like the [upload on GCS](https://github.com/triton-inference-server/server/blob/main/qa/common/util.sh#L471-L476), so it can be easily implemented by other AWS tests in the future.

This change has nothing to the remove bucket general step. 
It's a cleanup step that is required in order to prevent reaching us limit of 100 buckets, safety trigger for CI. 
IMO make no sense to move into function at this point.

**Comment by fpetrini15** [comment]
I do agree with Jacky that it would probably be better for maintenance purposes to consolidate these into a single function. That way there would only be a single point of change in the future if we need to modify/extend this. I can easily see someone forgetting to modify this command in 1+ locations.

**Comment by mc-nv** [comment]
> I do agree with Jacky that it would probably be better for maintenance purposes to consolidate these into a single, common function. That way there would only be a single point of change in the future if we need to modify/extend this. I can easily see someone forgetting to modify this command in 1+ locations.

What is the sense to replace single line with a function? 
Each scenario is separate one, adding function won't increase readability and understanding of the scenario. 
Further more `aws-cli` is itself multifunctional tool, there why putting more complex tool into wrapper is kind of not the best practice IMO

**Pull request closed without merging**
