### PR TITLE
OpenVINO 2023.3

### PR DESCRIPTION
**Pull request by atobiszei**
ONNX backend: https://github.com/triton-inference-server/onnxruntime_backend/pull/234

### CODE REVIEW

**Comment by kthui** [comment]
Hi @atobiszei, thanks for updating the OpenVINO version for Triton. We noticed there is an issue building OpenVINO on Windows `fatal: path 'versions/baseline.json' exists on disk, but not in 'db0473513e5dc73ec6b6f431ff05d2f398eea042'`. Would you be able to investigate further?
```
C:\workspace\openvino\build>cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/workspace/install -DENABLE_TESTS=OFF .. 
         -- Building for: Visual Studio 17 2022
         -- Running vcpkg install
    17>CUSTOMBUILD : error : while checking out baseline from commit 'db0473513e5dc73ec6b6f431ff05d2f398eea042', failed to `git show` versions/baseline.json. This may be fixed by fetching commits with `git fetch`. [C:\tmp\tritonbuild\openvino\build\ov_target.vcxproj]
    17>CUSTOMBUILD : error : git failed with exit code: (128). [C:\tmp\tritonbuild\openvino\build\ov_target.vcxproj]
         fatal: path 'versions/baseline.json' exists on disk, but not in 'db0473513e5dc73ec6b6f431ff05d2f398eea042'
         while checking out baseline db0473513e5dc73ec6b6f431ff05d2f398eea042
```

**Comment by atobiszei** [comment]
Hi @kthui could you share more details about your Windows machine? We did not encounter issues when building pure OV on Win11:

```
cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/temp/install -DENABLE_TESTS=OFF ..
cmake --build . --config Release --verbose -j8
```
Where does the commit sha db0473513e5dc73ec6b6f431ff05d2f398eea042 comes from? It is not OV 2023.3.0 tag.

**Comment by kthui** [comment]
Hi @atobiszei, the windows machine is running Windows 10 Enterprise version 20H2. The build is run on Docker which the base container is setup from [this instruction](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#windows-and-docker). All the build steps are then invoked by the `build.py`.

I think the commit sha db0473513e5dc73ec6b6f431ff05d2f398eea042 is from OpenVINO. See the "builtin-baseline" [here](https://github.com/openvinotoolkit/openvino/blob/master/vcpkg.json).

**Comment by mc-nv** [comment]
@kthui , suppose we had picked up this change, am I right?

**Pull request closed without merging**
