### PR TITLE
Improve L0_backend_python test stability (ensemble / gpu_tensor_lifecycle)

### PR DESCRIPTION
**Pull request by rmccorm4**
- Increase float comparison tolerance for ensemble test, reduce failures due to float noise
- Increase stability on gpu_tensor_lifecycle test by comparing directly with torch allocated memory. Global gpu memory can be noisy with other processes using it, and that testing can be deferred to more holistic gpu memory growth tests. I left in some logging of total gpu memory usage to aid future debugging if needed.

### CODE REVIEW

**Review by dyastremsky — APPROVED** [review]
Nice work!

**Review by Tabrizian — APPROVED** [review]
nice improvements!

**Review by krishung5 — APPROVED** [review]
Nice work, Ryan!

**Comment by rmccorm4** [comment]
Ran L0_backend_python 5 times and none failed due to either of these subtests, so seems like an improvement. Will monitor future tests for a bit.

**Pull request merged**
