### PR TITLE
Add OpenVINO autocomplete tests

### PR DESCRIPTION
**Pull request by kthui**
Core PR: https://github.com/triton-inference-server/core/pull/118
OpenVINO backend PR: https://github.com/triton-inference-server/openvino_backend/pull/44

### CODE REVIEW

**Comment by GuanLuo** [comment]
Are the model files the same? If so we can keep one copy and let `test.sh` to prepare the model directories.

**Comment by kthui** [comment]
Yes. The models are grouped.

**Comment by kthui** [comment]
Rebased.

**Comment by tanmayv25** [comment]
@kthui  Why are we putting model files in the repo? Why not use models from the model generator scripts? If there are few models that are missing, I would advice improving our gen scripts.

**Comment by kthui** [comment]
Add documentation about the model files in the repo, and adjusted the openvino dynamic_batch case to account for parsing default_max_batch_size.

**Review by tanmayv25 — APPROVED** [review]

**Pull request merged**
