### PR TITLE
Avoiding copy when reshaping the numpy array

### LINKED ISSUE #2384: Performance improvement for numpy decoding in Python client
**Description**
I am using the Python gRPC client for retrieving large 3D image segmentation probability maps per class. After digging into the code, the data access using `.as_numpy` is quite slow compared to the actual numpy computations I have to do.

https://github.com/triton-inference-server/server/blob/1028a53ccfed10176338196f7edf427ab86c7530/src/clients/python/library/tritonclient/grpc/__init__.py#L1588-L1631

**Triton Information**
docker nvcr.io/nvidia/tritonserver:20.08-py3
pip tritonclient==2.5.0

**To Reproduce**
```python
def async_callback(result, error):
    num_tries = 10
    for _ in range(num_tries):
        started = time.time()
        arr = result.as_numpy('output')
        print(f'Time for result.as_numpy {(time.time() - started) * 1000}ms')

    for idx, output in enumerate(result._result.outputs):
        shape = []
        for value in output.shape:
            shape.append(value)
        
        for _ in range(num_tries):
            started = time.time()
            byte_content = result._result.raw_output_contents[idx]
            print(f'Time for data access {(time.time() - started) * 1000}ms')

        for _ in range(num_tries):
            started = time.time()
            buf = np.frombuffer(result._result.raw_output_contents[idx], np.float32)
            buf = np.resize(buf, shape)
            print(f'Time for np.frombuffer+np.resize {(time.time() - started) * 1000}ms')
        
        for _ in range(num_tries):
            started = time.time()
            buf = np.frombuffer(result._result.raw_output_contents[idx], np.float32)
            buf = buf.resize(shape)
            print(f'Time for np.frombuffer+np.ndarray.resize {(time.time() - started) * 1000}ms')
        
        for _ in range(num_tries):
            started = time.time()
            buf = np.frombuffer(result._result.raw_output_contents[idx], np.float32)
            buf = np.reshape(buf, shape)
            print(f'Time for np.frombuffer+np.reshape {(time.time() - started) * 1000}ms')

        for _ in range(num_tries):
            started = time.time()
            buf = np.frombuffer(result._result.raw_output_contents[idx], np.float32)
            buf = buf.reshape(shape)
            print(f'Time for np.frombuffer+np.ndarray.reshape {(time.time() - started) * 1000}ms')

# Using gRPC
client = grpcclient.InferenceServerClient(url=triton_url)
input_tensor = grpcclient.InferInput('input', [1, 32, 512, 512, 1], 'INT16')
client.async_infer(
    model_name=model_name,
    model_version=model_version,
    inputs=[input_tensor],
    callback=async_callback
)
```
For a result output of type FP32 with shape `[1, 32, 512, 512, 11]` this produces the following log outputs:
```
Time for result.as_numpy 211.6074562072754ms
Time for result.as_numpy 208.95028114318848ms
Time for result.as_numpy 209.8860740661621ms
Time for result.as_numpy 209.18798446655273ms
Time for result.as_numpy 208.48894119262695ms
Time for result.as_numpy 210.02912521362305ms
Time for result.as_numpy 208.25576782226562ms
Time for result.as_numpy 209.20515060424805ms
Time for result.as_numpy 208.76812934875488ms
Time for result.as_numpy 208.54949951171875ms
Time for data access 124.60470199584961ms
Time for data access 133.45909118652344ms
Time for data access 134.25803184509277ms
Time for data access 134.60707664489746ms
Time for data access 134.27329063415527ms
Time for data access 134.05537605285645ms
Time for data access 133.99147987365723ms
Time for data access 134.2768669128418ms
Time for data access 134.22131538391113ms
Time for data access 133.35371017456055ms
Time for np.frombuffer+np.resize 207.66639709472656ms
Time for np.frombuffer+np.resize 208.10747146606445ms
Time for np.frombuffer+np.resize 208.33373069763184ms
Time for np.frombuffer+np.resize 208.20045471191406ms
Time for np.frombuffer+np.resize 207.3054313659668ms
Time for np.frombuffer+np.resize 208.23979377746582ms
Time for np.frombuffer+np.resize 208.22715759277344ms
Time for np.frombuffer+np.resize 206.76302909851074ms
Time for np.frombuffer+np.resize 207.40604400634766ms
Time for np.frombuffer+np.resize 207.04412460327148ms
Time for np.frombuffer+np.ndarray.resize 135.47492027282715ms
Time for np.frombuffer+np.ndarray.resize 135.67304611206055ms
Time for np.frombuffer+np.ndarray.resize 136.49845123291016ms
Time for np.frombuffer+np.ndarray.resize 134.66501235961914ms
Time for np.frombuffer+np.ndarray.resize 135.58030128479004ms
Time for np.frombuffer+np.ndarray.resize 136.11912727355957ms
Time for np.frombuffer+np.ndarray.resize 135.6372833251953ms
Time for np.frombuffer+np.ndarray.resize 134.62090492248535ms
Time for np.frombuffer+np.ndarray.resize 135.17475128173828ms
Time for np.frombuffer+np.ndarray.resize 135.27178764343262ms
Time for np.frombuffer+np.reshape 124.79782104492188ms
Time for np.frombuffer+np.reshape 133.68868827819824ms
Time for np.frombuffer+np.reshape 133.32533836364746ms
Time for np.frombuffer+np.reshape 133.05997848510742ms
Time for np.frombuffer+np.reshape 135.63084602355957ms
Time for np.frombuffer+np.reshape 133.05258750915527ms
Time for np.frombuffer+np.reshape 134.37414169311523ms
Time for np.frombuffer+np.reshape 134.4466209411621ms
Time for np.frombuffer+np.reshape 132.8599452972412ms
Time for np.frombuffer+np.reshape 132.76338577270508ms
Time for np.frombuffer+np.ndarray.reshape 132.89356231689453ms
Time for np.frombuffer+np.ndarray.reshape 132.34448432922363ms
Time for np.frombuffer+np.ndarray.reshape 132.62081146240234ms
Time for np.frombuffer+np.ndarray.reshape 132.24387168884277ms
Time for np.frombuffer+np.ndarray.reshape 134.36055183410645ms
Time for np.frombuffer+np.ndarray.reshape 132.44915008544922ms
Time for np.frombuffer+np.ndarray.reshape 133.87346267700195ms
Time for np.frombuffer+np.ndarray.reshape 132.22336769104004ms
Time for np.frombuffer+np.ndarray.reshape 132.80820846557617ms
Time for np.frombuffer+np.ndarray.reshape 133.06522369384766ms
```

**Issues**
1. The `np.resize(np_array, shape)` creates a new copy of the array and thus increases the actual decoding time by a lot.  `np_array.resize(shape)` reuses its own data and just updates the shape. However, `np.reshape(np_array, shape)` or `np_array.reshape(shape)` is still marginally faster. I don't know why `.resize` is used here instead of `.reshape`, but maybe there is an edge case I don't know.
3. Most problematic in my opinion is the actual data access. It takes over 130ms total decoding time to just access the byte content in `result._result.raw_output_contents[idx]`. This is no network communication overhead, since in this scenario the data is accessed multiple times with identical timings. Further, I would assume that at this point the data is already received and thus it should only be a memory pointer.

### PR DESCRIPTION
**Pull request by tanmayv25**
Partially addresses #2384

### CODE REVIEW

**Comment by CoderHam** [comment]
Can you fix the copyright year? These changes LGTM. I have been wondering if we want to create a python counterpart of the perf_client. It might be useful to measure the performance of our python library as compared to the C++ library.

**Review by CoderHam — APPROVED** [review]

**Comment by tanmayv25** [comment]
Thanks @CoderHam. Fixed the copyrights. 

As for python perf_client, we really want the users interested in performance to use C++ API. A fully-fledged python perf_client is possible but is too much of an effort. I don't think its utility is that important. Instead a very restrictive client that talks to an identity model(nomodel) collecting timing at each step and finally generating a report. This will help us in catching any regression which we might introduce accidentally.

**Review by Tabrizian — APPROVED** [review]

**Review by deadeyegoodwin — APPROVED** [review]

**Comment by deadeyegoodwin** [comment]
@Tabrizian  Are these types of improvements applicable to the python backend? If so can you file a ticket and refer to this PR so we can consider making the changes in the future.

**Comment by Tabrizian** [comment]
I think there are a couple of places, where I can apply this in the Python backend. I created a ticket for this.

**Pull request merged**
