### PR TITLE
Update build.md

### PR DESCRIPTION
**Pull request by alexanderkomarovincode3**
Update customisation_guide for CPU-only chapter. Because I just tried to build an image with `ensemble` backend, it really works!

### CODE REVIEW

**Comment by dyastremsky** [comment]
Thanks for submtiting this update! Have you submitted a signed contributor license agreement (CLA) yet? If not, please do so here: https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by alexanderkomarovincode3** [comment]
@dyastremsky Done. Thanks!

**Comment by dyastremsky** [comment]
Thank you, Alexander. We'll verify the build succeeds and update this PR once done.

**Comment by nv-kmcgill53** [comment]
CLA has been added.

**Review by nv-kmcgill53 — APPROVED** [review]

**Pull request merged**
