### PR TITLE
Add FIL backend to build.py

### PR DESCRIPTION
**Pull request by wphicks**

### CODE REVIEW

**Comment by wphicks** [comment]
Currently testing with:
```
./build.py --cmake-dir=./build --build-dir=/tmp/citritonbuild --enable-logging --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main --repo-tag=thirdparty:main --backend=fil:fea-buildpy
```

Builds successfully but server exits without error on first request.

**Comment by wphicks** [comment]
See https://github.com/triton-inference-server/fil_backend/pull/59 for FIL backend portion of this changeset.

**Comment by GuanLuo** [comment]
Segfault on the server side?

**Comment by wphicks** [comment]
Probably. I'll be investigating this morning.

**Comment by wphicks** [comment]
Server exit was not a real issue; got misled by a stale log file. Tested successfully with FIL's test suite. This is ready to go in as soon as https://github.com/triton-inference-server/fil_backend/pull/59 is in. I'll mark it is ready for review as soon as that is merged.

**Comment by wphicks** [comment]
@GuanLuo This is now ready for review.

**Review by GuanLuo — APPROVED** [review]

**Comment by JohnZed** [comment]
@deadeyegoodwin - would you mind merging this one?

**Comment by GuanLuo** [comment]
We are working on enabling it in CI, there are some changes required for a successful build. Once the changes are in and the CI passes, we will merge this change

**Pull request merged**
