### PR TITLE
fix: Downgrade ompi version to v4.1.5rc2

### PR DESCRIPTION
**Pull request by krishung5**
#### What does the PR do?

Downgrade ompi version to avoid ucc issues when running TRT-LLM container on kubernetes.

#### Checklist
- [x] PR title reflects the change and is of format `<commit_type>: <Title>`
- [x] Changes are described in the pull request.
- [ ] Related issues are referenced.
- [ ] Populated [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) field
- [x] Added [test plan](#test-plan) and verified test passes.
- [x] Verified that the PR passes existing CI.
- [x] Verified copyright is correct on all changed files.
- [ ] Added _succinct_ git squash message before merging [ref](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [ ] All template sections are filled out.
- [ ] Optional: Additional screenshots for behavior/output changes with before/after.

#### Commit Type:
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
- [x] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [ ] refactor
- [ ] revert
- [ ] style
- [ ] test

#### Test plan:

TRT-LLM backend build and tests should be passing.

- CI Pipeline ID: 16512052

#### Related Issues: (use one of the action keywords Closes / Fixes / Resolves / Relates to)
- closes GitHub issue: #xxx

### CODE REVIEW

**Review by fpetrini15 — APPROVED** [review]
LGTM, thanks for the fix 🚀

**Comment by krishung5** [comment]
@fpetrini15 FYI - though the TRT-LLM team says there shouldn't be issues for the downgrade, they are still trying to verify if there is any perf regression. Might worth waiting for their verification to merge this in.

**Review by fpetrini15 — CHANGES_REQUESTED** [review]
Dismissing approval until the TRT-LLM team verifies the fix

**Comment by krishung5** [comment]
Rebased

**Review by fpetrini15 — APPROVED** [review]

**Pull request merged**
