### PR TITLE
Enhance long term stress test

### PR DESCRIPTION
**Pull request by GuanLuo**
The PR is ready to review but not going to merge it until the following issues are addressed. It is a large PR but it can be reviewed commit by commit

- [x] Sequence ID collision when running multiple perf analyzer that happens to run against the same sequence model
- [x] Output validation feature in perf analyzer

### CODE REVIEW

**Review by deadeyegoodwin — DISMISSED** [review]

**Review by CoderHam — DISMISSED** [review]

**Review by deadeyegoodwin — APPROVED** [review]

**Comment by GuanLuo** [comment]
Re-enabled one of the perf analyzer tests as the issue is resolved by finishing sequences on changing concurrency. Lowering the max concurrency of the test because the model is already overloaded (can only serve ~ 1400 infer / sec), the original concurrency will cause some sequences to exceed timeout eventually.

Attached the stress report (10 min) after the changes
```
Test Duration: 00:10:49 (HH:MM:SS)
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| Test Case                  | Number of Failures | Test Count | Request Count | Test Case Description                             |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceValidScenario      | 0                  | 112        | 1762          | Send a sequence with "start" and "end" flags.     |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceValidValidScenario | 0                  | 28         | 542           | Send two sequences back to back using the same    |
|                            |                    |            |               | correlation ID with "start" and "end" flags.      |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceValidNoEndScenario | 0                  | 25         | 443           | Send two sequences back to back using the same    |
|                            |                    |            |               | correlation ID. The first with "start" and "end"  |
|                            |                    |            |               | flags, and the second with no "end" flag.         |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceNoStartScenario    | 0                  | 5          | 5             | Send a sequence without a "start" flag. Sequence  |
|                            |                    |            |               | should get an error from the server.              |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceNoEndScenario      | 0                  | 22         | 380           | Send a sequence with "start" flag but that never  |
|                            |                    |            |               | ends. The sequence should be aborted by the       |
|                            |                    |            |               | server and its slot reused for another sequence.  |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| TimeoutScenario            | 0                  | 20         | 20            | Expect an exception for small timeout values.     |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| ResNetScenario             | 0                  | 33         | 33            | Send a request using resnet model.                |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| CrashingScenario           | 0                  | 18         | 18            | Client crashes in the middle of inferences.       |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| PerfAnalyzerScenario       | 0                  | 141        | 141           | Client that maintains a specific load.            |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| TOTAL                      | 0                  | 404        | 3344          | X                                                 |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
```

**Comment by deadeyegoodwin** [comment]
Looking at the output table. Is resnet run using perf_analyzer? For resnet and PerfAnalyzerScenario is the number of requests the actual number of requests sent by perf_analyzer? That is what should be in the table.

**Comment by GuanLuo** [comment]
resnet is both an option in perf analyzer scenario and in its own scenario

**Comment by GuanLuo** [comment]
I made the change to log perf analyzer request count, but that kind of dominates the report
```
Test Duration: 00:01:45 (HH:MM:SS)
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| Test Case                  | Number of Failures | Test Count | Request Count | Test Case Description                             |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceValidScenario      | 0                  | 4          | 74            | Send a sequence with "start" and "end" flags.     |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceValidValidScenario | 0                  | 3          | 37            | Send two sequences back to back using the same    |
|                            |                    |            |               | correlation ID with "start" and "end" flags.      |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceValidNoEndScenario | 0                  | 2          | 29            | Send two sequences back to back using the same    |
|                            |                    |            |               | correlation ID. The first with "start" and "end"  |
|                            |                    |            |               | flags, and the second with no "end" flag.         |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceNoStartScenario    | 0                  | 0          | 0             | Send a sequence without a "start" flag. Sequence  |
|                            |                    |            |               | should get an error from the server.              |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| SequenceNoEndScenario      | 0                  | 2          | 36            | Send a sequence with "start" flag but that never  |
|                            |                    |            |               | ends. The sequence should be aborted by the       |
|                            |                    |            |               | server and its slot reused for another sequence.  |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| TimeoutScenario            | 0                  | 3          | 3             | Expect an exception for small timeout values.     |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| ResNetScenario             | 0                  | 2          | 64            | Send a request using resnet model.                |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| CrashingScenario           | 0                  | 2          | 2             | Client crashes in the middle of inferences.       |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| PerfAnalyzerScenario       | 0                  | 20         | 161285        | Client that maintains a specific load.            |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
| TOTAL                      | 0                  | 38         | 161530        | X                                                 |
+----------------------------+--------------------+------------+---------------+---------------------------------------------------+
```

**Review by deadeyegoodwin — APPROVED** [review]

**Review by CoderHam — APPROVED** [review]

**Pull request merged**
