### PR TITLE
build: fix building pip packages on ubuntu24

### PR DESCRIPTION
**Pull request by dtrawins**
#### What does the PR do?
Fix pip installation as root on python3.12 on ubuntu24

#### Checklist
- [x] PR title reflects the change and is of format `<commit_type>: <Title>`
- [x] Changes are described in the pull request.
- [ ] Related issues are referenced.
- [ ] Populated [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) field
- [ ] Added [test plan](#test-plan) and verified test passes.
- [ ] Verified that the PR passes existing CI.
- [ ] Verified copyright is correct on all changed files.
- [ ] Added _succinct_ git squash message before merging [ref](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [ ] All template sections are filled out.
- [ ] Optional: Additional screenshots for behavior/output changes with before/after.

#### Commit Type:
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
- [x] build
- [ ] ci
- [ ] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] revert
- [ ] style
- [ ] test

#### Test plan:

- CI Pipeline ID:

#### Related Issues: (use one of the action keywords Closes / Fixes / Resolves / Relates to)
- closes GitHub issue: #xxx

### CODE REVIEW

**Comment by mc-nv** [comment]
Triton server images out of release 24.11, does include that variable. 
Could you please rebase your branch. 
```
$ docker inspect --format='{{.Config.Env}}' nvcr.io/nvidia/tritonserver:24.11-py3
[PATH=/opt/tritonserver/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin:/opt/amazon/efa/bin CUDA_VERSION=12.6.3.001 CUDA_DRIVER_VERSION=560.35.05 CUDA_CACHE_DISABLE=1 NVIDIA_REQUIRE_JETPACK_HOST_MOUNTS= _CUDA_COMPAT_PATH=/usr/local/cuda/compat ENV=/etc/shinit_v2 BASH_ENV=/etc/bash.bashrc SHELL=/bin/bash NVIDIA_REQUIRE_CUDA=cuda>=9.0 NCCL_VERSION=2.23.4 CUBLAS_VERSION=12.6.4.1 CUFFT_VERSION=11.3.0.4 CURAND_VERSION=10.3.7.77 CUSPARSE_VERSION=12.5.4.2 CUSPARSELT_VERSION=0.6.3.2 CUSOLVER_VERSION=11.7.1.2 CUTENSOR_VERSION=2.0.2.5 NPP_VERSION=12.3.1.54 NVJPEG_VERSION=12.3.3.54 CUDNN_VERSION=9.5.1.17 CUDNN_FRONTEND_VERSION=1.8.0 TRT_VERSION=10.6.0.26 TRTOSS_VERSION= NSIGHT_SYSTEMS_VERSION=2024.6.1.90 NSIGHT_COMPUTE_VERSION=2024.3.2.3 DALI_VERSION=1.43.0 DALI_BUILD=19497385 POLYGRAPHY_VERSION=0.49.13 TRANSFORMER_ENGINE_VERSION=1.12 MODEL_OPT_VERSION=0.19.0 LD_LIBRARY_PATH=/opt/hpcx/ucc/lib/:/opt/hpcx/ucx/lib/:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 NVIDIA_VISIBLE_DEVICES=all NVIDIA_DRIVER_CAPABILITIES=compute,utility,video NVIDIA_PRODUCT_NAME=Triton Server GDRCOPY_VERSION=2.4.1 HPCX_VERSION=2.21 MOFED_VERSION=5.4-rdmacore39.0 OPENUCX_VERSION=1.18.0 OPENMPI_VERSION=4.1.7 RDMACORE_VERSION=39.0 EFA_VERSION=1.34.0 AWS_OFI_NCCL_VERSION=1.12.1 OPAL_PREFIX=/opt/hpcx/ompi OMPI_MCA_coll_hcoll_enable=0 LIBRARY_PATH=/usr/local/cuda/lib64/stubs: TRITON_SERVER_VERSION=2.52.0 NVIDIA_TRITON_SERVER_VERSION=24.11 UCX_MEM_EVENTS=no TF_ADJUST_HUE_FUSED=1 TF_ADJUST_SATURATION_FUSED=1 TF_ENABLE_WINOGRAD_NONFUSED=1 TF_AUTOTUNE_THRESHOLD=2 TRITON_SERVER_GPU_ENABLED=1 TRITON_SERVER_USER=triton-server DEBIAN_FRONTEND=noninteractive TCMALLOC_RELEASE_RATE=200 DCGM_VERSION=3.3.6 PIP_BREAK_SYSTEM_PACKAGES=1 PYTHONPATH=/opt/tritonserver/backends/dali/wheel/dali: NVIDIA_BUILD_ID=124543091]
```

**Comment by dtrawins** [comment]
@mc-nv The following command building the server from source fails:
```
 python3 build.py --target-platform linux --enable-logging --enable-stats --enable-metrics --enable-cpu-metrics --endpoint grpc --endpoint http --filesystem s3

Step 35/35 : RUN find /opt/tritonserver/python -maxdepth 1 -type f -name     "tritonserver-*.whl" | xargs -I {} pip install --upgrade {}[all] &&     find /opt/tritonserver/python -maxdepth 1 -type f -name     "tritonfrontend-*.whl" | xargs -I {} pip install --upgrade {}[all]
 ---> Running in 0bfd329d8a21
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by mc-nv** [comment]
Let me track this issue separately, it's a bug and we need to introduce a fix. 
The problem is that if Python backend doesn't included `build.py` is not able to handle the request properly.

**Comment by mc-nv** [comment]
@dtrawins could you please rebase your branch to current `main` the change we put in should solve your issue.

**Pull request closed without merging**
