### PR TITLE
Upgrade ORT to 1.13.1

### PR DESCRIPTION
**Pull request by pranavsharma**
Upgrade ORT to 1.13.1

### CODE REVIEW

**Review by dzier — DISMISSED** [review]

**Comment by dyastremsky** [comment]
@pranavsharma Do you know whether ORT 1.13 has precompiled CUDA support for Hopper?

**Comment by pranavsharma** [comment]
> Do you know whether ORT 1.13 has precompiled CUDA support for Hopper?

No, we don't support Hopper.

**Comment by dyastremsky** [comment]
Thanks for clarifying, Pranav.

**Comment by tanmayv25** [comment]
@pranavsharma We have moved our 22.10 release branch to use ORT 1.13.1.
https://github.com/triton-inference-server/server/commit/86427d61e44a78603d6fa1349e24fb087a574263
The main branch will start tracking ORT 1.13.1 once we release 22.10 containers. Closing this PR for now.

**Pull request closed without merging**
