### PR TITLE
ci: Enable TF-TRT tests

### PR DESCRIPTION
**Pull request by pskiran1**
#### What does the PR do?
This PR re-enables the L0_tftrt_optimization and L0_warmup TF-TRT tests that have been disabled since 24.05.

#### Checklist
- [x] PR title reflects the change and is of format `<commit_type>: <Title>`
- [x] Changes are described in the pull request.
- [ ] Related issues are referenced.
- [ ] Populated [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) field
- [x] Added [test plan](#test-plan) and verified test passes.
- [x] Verified that the PR passes existing CI.
- [x] Verified copyright is correct on all changed files.
- [ ] Added _succinct_ git squash message before merging [ref](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [ ] All template sections are filled out.
- [ ] Optional: Additional screenshots for behavior/output changes with before/after.

#### Commit Type:
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
- [ ] build
- [x] ci
- [ ] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] revert
- [ ] style
- [ ] test

#### Test plan:

- CI Pipeline ID: 16218566

#### Background
In the 24.05 release, implicit batch support was removed as part of the TRT v10 upgrade. As a result, the TF backend was unable to build TF-TRT engines for implicit batch TF models because it was using implicit batching by default. In the upcoming TF release, the TF backend will use dynamic batching by default, enabling it to successfully build TF-TRT models.

#### Related Issues: (use one of the action keywords Closes / Fixes / Resolves / Relates to)
- closes GitHub issue: #xxx

### CODE REVIEW

**Review by tanmayv25 — DISMISSED** [review]

**Comment by tanmayv25** [comment]
Don't merge just yet. Once the r24.07 branch is ready, then merge these changes into that branch.

**Comment by krishung5** [comment]
@pskiran1 Could you change the target branch to `r24.07`?

**Review by krishung5 — APPROVED** [review]

**Comment by mc-nv** [comment]
can we change target branch to `main` I don't see any value in this change for release branch.

**Comment by krishung5** [comment]
@mc-nv I have no strong objections to change it to target `main` since it's only change in comments in the tests, but I would still slightly prefer to merge it into the release branch first, then merge into `main` after 24.07 gets released. The reason being that, the implicit batch will only be supported from 24.07 upstream while as of now the `main` hasn't been advanced to 24.07 DLFW yet and hence doesn't have the support for implicit batch.

**Pull request merged**
