### PR TITLE
Update TRT model gen to support TRT 8

### PR DESCRIPTION
**Pull request by CoderHam**

### CODE REVIEW

**Comment by CoderHam** [comment]
Tested with the latest TRT container (with 8.0.1.6) and the models were generated correctly. 
cc @msalehiNV

**Review by deadeyegoodwin — COMMENTED** [review]
Looks good but not approving for now because this must go into the r21.07 branch, not main.

**Comment by CoderHam** [comment]
Right. I'll share the destination branch once r21.07 is ready
cc @dzier

**Comment by CoderHam** [comment]
> Right. I'll share the destination branch once r21.07 is ready
> cc @dzier

Done

**Comment by CoderHam** [comment]
Closing since already in 21.07

**Pull request closed without merging**
