### PR TITLE
Rename client container to sdk container

### PR DESCRIPTION
**Pull request by Tabrizian**

### CODE REVIEW

**Comment by CoderHam** [comment]
Please make the rename changes in `client_libraries.md` as well

**Review by CoderHam — CHANGES_REQUESTED** [review]
Your GitHub changes the dockerfile to Dockerfile.tritonsdk however the gitlab assumes it as Dockerfile.sdk. 

In my opinion I would recommend Dockerfile.sdk since we do not prefix triton to any of the other Dockerfiles i.e. we had Dockerfile.client and not Dockerfile.tritonclient

**Comment by Tabrizian** [comment]
That PR was old. I closed it and opened a new PR.

**Review by CoderHam — APPROVED** [review]

**Review by deadeyegoodwin — CHANGES_REQUESTED** [review]
Just need Dockerfile.client  -> Dockerfile.sdk name change

**Review by CoderHam — APPROVED** [review]

**Review by deadeyegoodwin — APPROVED** [review]

**Pull request merged**
