### PR TITLE
Bump vllm to v0.4.2

### PR DESCRIPTION
**Pull request by kebe7jun**

### CODE REVIEW

**Comment by rmccorm4** [comment]
Hi @kebe7jun, thanks for submitting the PR.

Can you elaborate on the specific models or features you're interested in that require this version upgrade?

CC @oandreeva-nv @tanmayv25

**Comment by oandreeva-nv** [comment]
Started internal CI: 14897042
@kebe7jun , by any chance, have you submitted Triton [CLA](https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) already?

**Comment by kebe7jun** [comment]
I need LLama3 optimizations from 0.4.1, as well as phi-3-mini support from 0.4.2. See: https://github.com/vllm-project/vllm/releases

I have already signed the CLA, and I have had [PR](https://github.com/triton-inference-server/server/pull/6918) merged before.

**Comment by oandreeva-nv** [comment]
@rmccorm4 , yesy, I was working on this. In latest vllm they've added installation of `pynvml` to the requirements, so it conflicts with whatever we re-install in multi-gpu tests and as a result fails it. I was doing some initial tests with removing `pynvml` from tests, but it still was failing. Didn't get a chance to debug further as got re-assigned

**Comment by pskiran1** [comment]
@kebe7jun, please rebase your branch with the latest main. Thank you.

**Review by oandreeva-nv — APPROVED** [review]
LGTM with @pskiran1 changes: https://github.com/triton-inference-server/vllm_backend/pull/43

**Pull request merged**
