### PR TITLE
Update vLLM to 0.3.2 for gemma support

### PR DESCRIPTION
**Pull request by kebe7jun**
https://github.com/vllm-project/vllm/releases/tag/v0.3.2

### CODE REVIEW

**Comment by rmccorm4** [comment]
Hi @kebe7jun, thanks for the contribution! Have you submitted a [CLA](https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla)?

**Comment by oandreeva-nv** [comment]
Started pipeline: 13151556

**Comment by kebe7jun** [comment]
> Hi @kebe7jun, thanks for the contribution! Have you submitted a [CLA](https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla)?

I've completed the process.

**Comment by nv-kmcgill53** [comment]
We have accepted your CLA. We are able to merge this PR at our discretion. Thank you for contributing to the Triton Project!

**Comment by oandreeva-nv** [comment]
Pipeline is green. Merging

**Pull request merged**
