### PR TITLE
test: Add input byte size tests using C APIs

### PR DESCRIPTION
**Pull request by yinggeh**
#### What does the PR do?
Copies executable to qa/L0_input_validation directory and depended models to qa/L0_input_validation/models.

#### Checklist
- [x] PR title reflects the change and is of format `<commit_type>: <Title>`
- [x] Changes are described in the pull request.
- [x] Related issues are referenced.
- [ ] Populated [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) field
- [x] Added [test plan](#test-plan) and verified test passes.
- [x] Verified that the PR passes existing CI.
- [x] Verified copyright is correct on all changed files.
- [x] Added _succinct_ git squash message before merging [ref](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [x] All template sections are filled out.
- [ ] Optional: Additional screenshots for behavior/output changes with before/after.

#### Commit Type:
- [x] test

#### Related PRs:
https://github.com/triton-inference-server/core/pull/374

#### Where should the reviewer start?
N/A

#### Test plan:

- CI Pipeline ID:
16290532

#### Caveats:
N/A

#### Background
1. Adding server level input byte size checks (TBD) will invalidate current tests in L0_input_validation since the error returned from server will be different from core.
2. Some sophisticated logics were added in infer_request.cc that requires granular C API tests. See https://github.com/triton-inference-server/core/pull/364

#### Related Issues: (use one of the action keywords Closes / Fixes / Resolves / Relates to)
N/A

### CODE REVIEW

**Review by GuanLuo — DISMISSED** [review]

**Comment by yinggeh** [comment]
@GuanLuo I failed to include the test binary `input_byte_size_test` in `L0_input_validation`. Can you kindly review and approve?

**Comment by yinggeh** [comment]
Updated CI Pipeline ID @GuanLuo

**Review by GuanLuo — DISMISSED** [review]

**Review by GuanLuo — APPROVED** [review]

**Comment by kthui** [comment]
@yinggeh just wondering if you have tried building on `cpu-only-py3-base`?

I'm getting this error could be related to this change
```
CMake Error at test/CMakeLists.txt:681 (target_link_libraries):
  Target "input_byte_size_test" links to:
    CUDA::cudart
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
jobs #99919520

**Comment by yinggeh** [comment]
@kthui Looks like `cpu-only-py3-base` is skipped by default (pipeline ID 16290505). I can quickly fix it.

**Pull request merged**
