### PR TITLE
Add tests for batch size reporting

### PR DESCRIPTION
**Pull request by Tabrizian**

### CODE REVIEW

**Review by CoderHam — APPROVED** [review]

**Comment by GuanLuo** [comment]
I believe our L0_batcher and L0_sequence_batcher tests will check the model stats, is the Python backend not being included in the test?

**Comment by Tabrizian** [comment]
@GuanLuo Yes, Python backend is not part of `L0_batcher` or `L0_sequence_batcher`.

**Comment by CoderHam** [comment]
> @GuanLuo Yes, Python backend is not part of `L0_batcher` or `L0_sequence_batcher`.

Do we want to batcher and sequence batcher test coverage for the python backend? If so we should have a ticket for the same.

**Comment by Tabrizian** [comment]
I created the ticket for it.

**Pull request merged**
