### PR TITLE
fix: openai chat message dump logic

### PR DESCRIPTION
**Pull request by dongs0104**
#### What does the PR do?
I found an issue with the OpenAI message format where user messages that are not strings are automatically converted to strings by the code, resulting in a `[ChatCompletionResponseMessageContentPart(text="~~~")]` string conversion problem. I have fixed this issue.

#### Checklist
- [x] I have read the [Contribution guidelines](#../../CONTRIBUTING.md) and signed the [Contributor License
Agreement](https://github.com/NVIDIA/triton-inference-server/blob/master/Triton-CCLA-v1.pdf)
- [x] PR title reflects the change and is of format `<commit_type>: <Title>`
- [x] Changes are described in the pull request.
- [ ] Related issues are referenced.
- [ ] Populated [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) field
- [ ] Added [test plan](#test-plan) and verified test passes.
- [ ] Verified that the PR passes existing CI.
- [x] I ran pre-commit locally (`pre-commit install, pre-commit run --all`)
- [ ] Verified copyright is correct on all changed files.
- [ ] Added _succinct_ git squash message before merging [ref](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [ ] All template sections are filled out.
- [ ] Optional: Additional screenshots for behavior/output changes with before/after.

#### Commit Type:
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [x] refactor
- [ ] revert
- [ ] style
- [ ] test

#### Related PRs:
#7561

#### Where should the reviewer start?

@rmccorm4 

#### Background
To fix the issue of ChatCompletionResponseMessageContentPart being mixed with the output

#### Related Issues: (use one of the action keywords Closes / Fixes / Resolves / Relates to)
- closes GitHub issue: #xxx

### CODE REVIEW

**Comment by rmccorm4** [comment]
Hi @dongs0104, thanks for contributing this fix! 

1. Have you emailed a signed CLA as described here: https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla?
2. Can you share an example request/payload that would produce this string conversion problem before your fix so we can add a test case?

**Comment by dongs0104** [comment]
@rmccorm4 i signed it and add test case

**Comment by rmccorm4** [comment]
Started pipeline: 21452308

**Comment by rmccorm4** [comment]
Hi @dongs0104,

Have you tested this is passing locally? 

I get a schema validation error on your new test case (return code 422) because content is expected to be a `string` or `List[dict]`, but you're passing a `dict` directly: https://github.com/triton-inference-server/server/blob/bcff3da7faccd18ea62316bf4e19d47cbfa7412c/python/openai/openai_frontend/schemas/openai.py#L659
 
Your test case:
```python
messages = [
            {
                "role": "user",
                "content": {"type": "text", "text": "What is machine learning?"},
            }
        ]
```

Expected Schema: (note the list `[ ]`)
```python
messages = [
            {
                "role": "user",
                "content": [{"type": "text", "text": "What is machine learning?"}], 
            }
        ]
```

I think this should get the test to pass.

**Comment by dongs0104** [comment]
@rmccorm4 i tested it after your comment thanks

**Comment by nv-kmcgill53** [comment]
CLA has been accepted. This PR can be merged at Triton's discretion.

**Review by rmccorm4 — APPROVED** [review]

**Comment by rmccorm4** [comment]
Thanks for your contribution @dongs0104!

**Pull request merged**
